backend/urls.py
from django.urls import path

from . import views

app_name = 'backend'
urlpatterns = [
    path('', views.index, name='index'),
    path('customer/', views.CustomerView.as_view(), name='customer'),
    path('customer/<int:customer_id>/', views.customerdetail, name='customer_detail'),
    path('product/', views.product, name='product'),
    path('product/<int:product_id>/', views.productdetail, name='product_detail'),
    path('order/', views.order, name='order'),
    path('order/<int:order_id>/', views.orderdetail, name='order_detail'),
    path('inventory/', views.inventory, name='inventory'),
    path('inventory/<int:inventory_id>', views.inventorydetail, name='inventory_detail'),
    path('newshoppingcart/', views.newshoppingcart, name='newshoppingcart'),
    path('shoppingcart/<int:order_id>', views.shoppingcart, name='shoppingcart'),
    path('addtocart/', views.addtocart, name='addtocart'),
    path('removefromcart/', views.removefromcart, name='removefromcart'),
    path('selectcustomer/', views.selectcustomer, name='selectcustomer'),
    path('setcustomer/', views.setcustomer, name='setcustomer'),
    path('addpayment/', views.addpayment, name='addpayment'),
    path('addshipping/', views.addshipping, name='addshipping'),
    path('addcustomer/', views.addcustomer, name='addcustomer'),
    path('updatecustomer/', views.updatecustomer, name='updatecustomer'),
]

xigua_shopping/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('backend.urls')),
]

backend/models.py
from django.db import models
from django.utils import timezone

import datetime

class Customer(models.Model):
    cid = models.AutoField(primary_key=True)
    cname = models.CharField('Name', max_length=20)
    caddr = models.CharField('Address', max_length=100, null=True)
    cphone = models.CharField('Phone', max_length=15, null=True)
    cwechat = models.CharField('Wechat', max_length=20, null=True)
    cdate = models.DateTimeField('Date Created', null=True)
    cnote = models.CharField('Note', max_length=100, null=True)

    def __str__(self):
        return self.cname
    @classmethod
    def create(cls, name):
        customer = cls(cname=name, cdate=timezone.now())
        customer.save()
        return customer

class Order(models.Model):
    oid = models.AutoField(primary_key=True)
    cid = models.ForeignKey('Customer', on_delete=models.CASCADE)
    odate = models.DateTimeField('Date Ordered')
    oshipdate = models.DateTimeField('Date Shipped', null=True)
    opaid = models.BooleanField('Is this order paid?')
    ototal = models.DecimalField('Total amount', max_digits=10, decimal_places=2, null=True)
    oshipping = models.DecimalField('Shipping Cost', max_digits=10, decimal_places=2, null=True)
    opaymentmethod = models.CharField('Payment method', max_length=20, null=True)
    ostatus = models.CharField('Status', max_length=20)
    onote = models.CharField('Note', max_length=100, null=True)

    def __str__(self):
        return str(self.oid)

    @classmethod
    def create(cls):
        tmpCustomer = Customer.objects.filter(cid=1)[0]
        order = cls(cid=tmpCustomer, odate=timezone.now(), opaid=0, 
                    ostatus="pending", onote="temporary order")
        order.save()
        return order

class Product(models.Model):
    pid = models.AutoField(primary_key=True)
    pname = models.CharField('Product Name', max_length=40)
    ptype = models.CharField('Product Type', max_length=20, null=True)
    pcost = models.DecimalField('Product Cost', max_digits=10, decimal_places=2, null=True)
    pprice = models.DecimalField('Product Price', max_digits=10, decimal_places=2, null=True)
    pweight = models.DecimalField('Weight', max_digits=10, decimal_places=2, null=True)
    pstatus = models.CharField('Status', max_length=15, null=True)
    pnote = models.CharField('Note', max_length=100, null=True)

    def __str__(self):
        return self.pname

class Ordercontains(models.Model):
    oid = models.ForeignKey('Order', on_delete=models.CASCADE)
    pid = models.ForeignKey('Product', on_delete=models.CASCADE)
    oquantity = models.IntegerField('Order Quantity')
    oprice = models.DecimalField('Order Price', max_digits=10, decimal_places=2)

    class Meta:
        unique_together = (('oid', 'pid'))
    def __str__(self):
        return str(self.oid) + " " + str(self.pid)
    @classmethod
    def create(cls, order, product, quantity, price):
        oc = cls(oid=order, pid=product, oquantity=quantity, oprice=price)
        oc.save()
        return oc

class Inventory(models.Model):
    iid = models.AutoField(primary_key=True)
    idate = models.DateTimeField('Date Received')
    icost = models.DecimalField('Total Value', max_digits=10, decimal_places=2)
    ishipping = models.DecimalField('Shipping Cost', max_digits=10, decimal_places=2)
    itype = models.CharField('Shipping Method', max_length=20, null=True)
    inote = models.CharField('Note', max_length=100, null=True)

    def __str__(self):
        return str(self.iid)
    
class Inventorycontains(models.Model):
    iid = models.ForeignKey('Inventory', on_delete=models.CASCADE)
    pid = models.ForeignKey('Product', on_delete=models.CASCADE)
    iquantity = models.IntegerField('Inventory Quantity')
    iprice = models.DecimalField('Inventory Price', max_digits=10, decimal_places=2)

    class Meta:
        unique_together = (('iid', 'pid'))
    def __str__(self):
        return str(self.iid) + " " + str(self.pid)

backend/views/customer.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from django.views import generic
from django.db import connection
from django.contrib.auth.decorators import login_required
from backend.models import Customer, Order, Product, Inventory


class CustomerView(generic.ListView):
    template_name = 'backend/customer.html'
    context_object_name = 'customer_list'

    def get_queryset(self):
        return Customer.objects.raw('SELECT * FROM backend_customer ORDER BY cid')

def addcustomer(request):
    customer = Customer.create(request.POST['name'])
    if (request.POST['address'] != ""):
        customer.caddr = request.POST['address'] 
    if (request.POST['phone'] != ""):
        customer.cphone = request.POST['phone'] 
    if (request.POST['wechat'] != ""):
        customer.cwechat = request.POST['wechat'] 
    if (request.POST['note'] != ""):
        customer.cnote = request.POST['note'] 
    customer.save()
    return redirect("/customer/" + str(customer.cid))

def updatecustomer(request):
    customer = Customer.objects.filter(cid=request.POST['cid'])[0]
    if (request.POST['name'] != ""):
        customer.cname = request.POST['name']
    if (request.POST['address'] != ""):
        customer.caddr = request.POST['address']
    if (request.POST['phone'] != ""):
        customer.cphone = request.POST['phone'] 
    if (request.POST['wechat'] != ""):
        customer.cwechat = request.POST['wechat'] 
    if (request.POST['note'] != ""):
        customer.cnote = request.POST['note'] 
    customer.save()
    return redirect("/customer/" + str(customer.cid))

backend/views/customerdetail.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.views import generic
from django.db import connection
from django.contrib.auth.decorators import login_required
from backend.models import Customer, Order, Product, Inventory
from .util import *


def customerdetail(request, customer_id):
    customer = get_object_or_404(Customer, pk=customer_id)
    template_name = 'backend/customer_detail.html'
#    orders = Order.objects.filter(cid_id=customer.cid);
    orders = get_customer_orders(customer_id)
    return render(request, template_name, {
        'customer': customer,
        'message': "hello cash",
        'orders': orders,
    })

def get_customer_orders(customer_id):
    with connection.cursor() as cursor:
        cursor.execute('''
                        SELECT *
                        FROM backend_customer AS C JOIN backend_order AS O ON C.cid = O.cid_id
                        WHERE C.cid = %s
                        ''', [customer_id])
        res = dictfetchall(cursor)
        return res

backend/views/index.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.views import generic
from django.db import connection
from django.contrib.auth.decorators import login_required
from backend.models import Customer, Order, Product, Inventory

#@login_required
def index(request):
    return render(request, 'backend/index.html')

backend/views/inventory.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.views import generic
from django.db import connection
from django.contrib.auth.decorators import login_required
from backend.models import Customer, Order, Product, Inventory

def inventory(request):
    inventory = Inventory.objects.all()
    template_name = 'backend/inventory.html'
    return render(request, template_name, {
        'inventory': inventory,
    })

backend/views/inventorydetail.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.views import generic
from django.db import connection
from django.contrib.auth.decorators import login_required
from backend.models import Customer, Order, Product, Inventory
from .util import *

def inventorydetail(request, inventory_id):
    inventory = get_object_or_404(Inventory, pk=inventory_id)
    template_name = 'backend/inventory_detail.html'
    items = get_inventory_items(inventory_id)
    return render(request, template_name, {
        'inventory': inventory,
        'items': items,
    })
    
def get_inventory_items(inventory_id):
    with connection.cursor() as cursor:
        cursor.execute('''
                        SELECT *
                        FROM backend_inventory AS I JOIN backend_inventorycontains AS IC ON I.iid = IC.iid_id JOIN backend_product AS P ON P.pid = IC.pid_id
                        WHERE I.iid = %s
                        ''', [inventory_id])
        res = dictfetchall(cursor)
        return res

backend/views/order.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.views import generic
from django.db import connection
from django.contrib.auth.decorators import login_required
from backend.models import Customer, Order, Product, Inventory
from .util import *


def order(request):
    order = get_all_orders()
    pendingorder = get_pending_orders()
    paidorder = get_paid_orders()
    shippedorder = get_shipped_orders()
    completedorder = get_completed_orders()
    template_name = 'backend/order.html'
    return render(request, template_name, {
        'order': order,    
        'pendingorder': pendingorder,
        'paidorder': paidorder,
        'shippedorder': shippedorder,
        'completedorder': completedorder,
    }) 

def get_all_orders():
    with connection.cursor() as cursor:
        cursor.execute('''
                        SELECT *
                        FROM backend_order AS O JOIN backend_customer AS C ON O.cid_id = C.cid
                        ORDER BY O.odate DESC 
                        ''')
        res = dictfetchall(cursor)
        return res

def get_pending_orders():
    with connection.cursor() as cursor:
        cursor.execute('''
                        SELECT *
                        FROM backend_order AS O JOIN backend_customer AS C ON O.cid_id = C.cid
                        WHERE ostatus="pending"
                        ORDER BY O.odate DESC 
                        ''')
        res = dictfetchall(cursor)
        return res

def get_paid_orders():
    with connection.cursor() as cursor:
        cursor.execute('''
                        SELECT *
                        FROM backend_order AS O JOIN backend_customer AS C ON O.cid_id = C.cid
                        WHERE ostatus="paid"
                        ORDER BY O.odate DESC 
                        ''')
        res = dictfetchall(cursor)
        return res

def get_shipped_orders():
    with connection.cursor() as cursor:
        cursor.execute('''
                        SELECT *
                        FROM backend_order AS O JOIN backend_customer AS C ON O.cid_id = C.cid
                        WHERE ostatus="shipped"
                        ORDER BY O.odate DESC 
                        ''')
        res = dictfetchall(cursor)
        return res
    
def get_completed_orders():
    with connection.cursor() as cursor:
        cursor.execute('''
                        SELECT *
                        FROM backend_order AS O JOIN backend_customer AS C ON O.cid_id = C.cid
                        WHERE ostatus="completed"
                        ORDER BY O.odate DESC 
                        ''')
        res = dictfetchall(cursor)
        return res

backend/views/orderdetail.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from django.views import generic
from django.db import connection
from django.contrib.auth.decorators import login_required
from django.utils import timezone

from backend.models import Customer, Order, Product, Inventory
from .util import *


def orderdetail(request, order_id):
    order = get_object_or_404(Order, pk=order_id)
    template_name = 'backend/order_detail.html'
    items = get_order_items(order_id)
    customer = Customer.objects.filter(order__oid=order_id)[0]
    return render(request, template_name, {
        'order': order,
        'items': items,
        'customer': customer,
    })

def get_order_items(order_id):
    with connection.cursor() as cursor:
        cursor.execute('''
                        SELECT *
                        FROM backend_order AS O JOIN backend_ordercontains AS OC ON O.oid = OC.oid_id JOIN backend_product AS P ON P.pid = OC.pid_id
                        WHERE O.oid = %s
                        ''', [order_id])
        res = dictfetchall(cursor)
        return res

def addpayment(request):
    order = Order.objects.filter(oid=request.POST['oid'])[0]
    order.opaid = 1
    order.ototal = request.POST['total']
    order.opaymentmethod = request.POST['paymentmethod']
    order.ostatus = "paid"
    if (request.POST['note'] != ""):
        order.onote = request.POST['note']
    order.save()
    return redirect("/order/" + str(request.POST['oid']))

def addshipping(request):
    order = Order.objects.filter(oid=request.POST['oid'])[0]
    order.oshipping = request.POST['shipping']
    order.oshipdate = timezone.now()
    order.ostatus = "shipped"
    if (request.POST['note'] != ""):
        order.onote = request.POST['note']
    order.save()
    return redirect("/order/" + str(request.POST['oid']))

backend/views/product.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.views import generic
from django.db import connection
from django.contrib.auth.decorators import login_required
from backend.models import Customer, Order, Product, Inventory
from .util import *


def product(request):
    foodproduct = get_food_products()
    healthproduct = Product.objects.filter(ptype="Health")
    template_name = 'backend/product.html'
    return render(request, template_name, {
        'foodproduct': foodproduct,
        'healthproduct': healthproduct,
    })

def get_food_products():
    with connection.cursor() as cursor:
        cursor.execute('''
                       SELECT PIN.pid, pname, PIN.ptype, pcost, pprice, PIN.sin AS sin, POUT.sout AS sout, (PIN.sin - POUT.sout) AS soh
                       FROM 
                            (SELECT pid, pname, ptype, pcost, pprice, SUM(iquantity) AS sin 
                            FROM backend_product P LEFT OUTER JOIN backend_inventorycontains IC on P.pid = IC.pid_id
                            WHERE ptype = "Food"
                            GROUP BY pid) AS PIN
                       LEFT OUTER JOIN 
                            (SELECT pid, SUM(oquantity) AS sout
                             FROM backend_product P LEFT OUTER JOIN backend_ordercontains OC on P.pid = OC.pid_id
                             WHERE ptype = "Food"
                             GROUP BY pid) AS POUT
                       ON PIN.pid = POUT.pid;
                       ''')
        res = dictfetchall(cursor)
        return convertNullToZero(res)

def convertNullToZero(dic):
    for row in dic:
        if (row['sin'] == None):
            row['sin'] = 0
        if (row['sout'] == None):
            row['sout'] = 0
        if (row['soh'] == None):
            row['soh'] = row['sin'] - row['sout']
    return dic

backend/views/productdetail.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.views import generic
from django.db import connection
from django.contrib.auth.decorators import login_required
from backend.models import Customer, Order, Product, Inventory
from .util import *

def productdetail(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    template_name = 'backend/product_detail.html'
    return render(request, template_name, {
        'product': product,
    })
    

backend/views/util.py
def dictfetchall(cursor):
    columns = [col[0] for col in cursor.description]
    return [dict(zip(columns, row)) for row in cursor.fetchall()]

backend/templates/backend/inventory.html
{% extends 'backend/includes/header.html' %}

{% block content %}
    <div class="container">
        <h1>Inventory</h1>
    </div>
    
    <div class="container">
    {% if inventory %}
        <div class="row">
            <div class="col">
                <table class="table table-striped table-hover">
                    <thead class="thead-dark">
                    <tr>
                        <th style="width:10%;">iid</th>
                        <th style="width:70%;">Date</th>
                        <th style="width:20%;">Type</th>
                    </tr>
                    </thead>
                    {% for i in inventory %}
                    <tr onclick="window.location='{% url 'backend:inventory_detail' i.iid %}';">
                        <td><a href="{% url 'backend:inventory_detail' i.iid %}">{{ i.iid }}</a></td>
                        <td>{{ i.idate|date:"m/d/Y" }}</td>
                        <td>{{ i.itype }}</td>
                    </tr>   
                    {% endfor %}
                </table>

            </div>
        </div>

    {% else %}
        <p>No inventoriess are available.</p>
    {% endif %}
    </div>


{% endblock %}

backend/templates/backend/order_detail.html
{% extends 'backend/includes/header.html' %}

{% block content %}

	<div class="container">
	  <h1>Order Detail</h1>
	  <div class="row">
	  	<div class="col-8">
			<table class="table">
			  <tbody>
			    <tr>
			      <td style="width:40%"">Customer</td>
			      <td style="width:60%"">
					<a href='{% url 'backend:customer_detail' customer.cid %}'> {{ customer.cname }} </a>
			      </td>
			    </tr>
			    <tr>
			      <td>Order ID</td>
			      <td>{{ order.oid }}</td>
			    </tr>
			    <tr>
			      <td>Order Date</td>
			      <td>{{ order.odate|date:"m/d/Y H:i" }}</td>
			    </tr>
			    <tr>
			      <td>Ship Date</td>
			      <td>{{ order.oshipdate|date:"m/d/Y H:i" }}</td>
			    </tr>				    
			    <tr>
			      <td>Paid</td>
		      		{% if order.opaid == 0 %}
						<td>No</td>
					{% else %}
						<td>Yes</td>
					{% endif %}
			    </tr>    
			    <tr>
			      <td>Total</td>
			      <td>{{ order.ototal }}</td>
			    </tr>			    			    
			    <tr>
			      <td>Shipping Fee</td>
			      <td>{{ order.oshipping }}</td>
			    </tr>	
			    <tr>
			      <td>Payment Method</td>
			      <td>{{ order.opaymentmethod }}</td>
			    </tr>	
			    <tr>
			      <td>Status</td>
			      <td>{{ order.ostatus }}</td>
			    </tr>	
			    <tr>
			      <td>Note</td>
			      <td>{{ order.onote }}</td>
			    </tr>	
			  </tbody>
			</table>
		</div>
		<div class="col-4"></div>
	  </div>
	</div>

	<div class="container">
		<a href="{% url 'backend:shoppingcart' order.oid %}" class="btn btn-warning" role="button">Edit Shopping Cart</a>
		<a href="#addPayment" data-toggle="collapse" class="btn btn-info">Add Payment</a>
		<a href="#addShipping" data-toggle="collapse" class="btn btn-success" role="button">Add Shipping</a>
		<hr>
	</div>

	<div class="container collapse" id="addPayment">
	<form action='{% url 'backend:addpayment' %}' method="post">
		{% csrf_token %}
		<input type="hidden" name="oid" value={{ order.oid }}>
		<div class="form-group">
			<label>Total</label>
			<input type="number" class="form-control" name="total" step="0.01">
		</div>
		<div class="form-group">
			<label>Payment Method</label>
			<br>
			<label class="radio-inline mr-2"><input type="radio" name="paymentmethod" value="venmo">Venmo</label>
			<label class="radio-inline mr-2"><input type="radio" name="paymentmethod" value="paypal">Paypal</label>
			<label class="radio-inline mr-2"><input type="radio" name="paymentmethod" value="cash">Cash</label>
			<label class="radio-inline mr-2"><input type="radio" name="paymentmethod" value="other">Other</label>
		</div>
		<div class="form-group">
			<label>Note</label>
			<input type="text" class="form-control" name="note">
		</div>
		<button type="submit" class="btn btn-primary">Submit</button>
	</form>
	<hr>
	</div>
	
	<div class="container collapse" id="addShipping">
	<form action='{% url 'backend:addshipping' %}' method="post">
		{% csrf_token %}
		<input type="hidden" name="oid" value={{ order.oid }}>
		<div class="form-group">
			<label>Shipping Fee</label>
			<input type="number" class="form-control" name="shipping" step="0.01">
		</div>
		<div class="form-group">
			<label>Note</label>
			<input type="text" class="form-control" name="note">
		</div>
		<button type="submit" class="btn btn-primary">Submit</button>
	</form>
	<hr>
	</div>

	<div class="container">
	{% if items %}
		<div class="row justify-content-start">
			<div class="col">
				<table class="table table-striped table-hover">
					<thead class="thead-dark">
					<tr>
						<th style="width:50%;">Product Name</th>
						<th style="width:25%;">Quantity</th>
						<th style="width:25%;">Price</th>
					</tr>
					</thead>
					{% for item in items %}
					<tr onclick="window.location='{% url 'backend:product_detail' item.pid %}';">
						<td><a href="{% url 'backend:product_detail' item.pid %}" >{{ item.pname }}</a></td>
						<td>{{ item.oquantity }}</td>
						<td>{{ item.oprice }}</td>
					</tr>	
					{% endfor %}
				</table>

			</div>
		</div>
	{% else %}
	    <p>No items are available.</p>
	{% endif %}
	</div>

{% endblock %}

backend/templates/backend/shoppingcart.html
{% extends 'backend/includes/header.html' %}

{% block content %}
	{% load backend_filters %}
	<div class="container">
    	<h1>Shopping Cart</h1>		
	</div>

	<div class="container">
		<p>Order ID: {{ order.oid }}</p>
	</div>

	<div class="container">
	{% if items %}
		<div class="row justify-content-start">
			<div class="col">
				<table class="table table-striped table-hover">
					<thead class="thead-dark">
					<tr>
						<th style="width:30%;">Product Name</th>
						<th style="width:25%;">Price</th>
						<th style="width:25%;">Quantity</th>
						<th style="width:10%;">Update</th>
						<th style="width:10%;">Remove</th>
					</tr>
					</thead>
					{% for item in items %}
					<tr>
						<td><a href="{% url 'backend:product_detail' item.pid %}" >{{ item.pname }}</a></td>
						<form action='{% url 'backend:addtocart' %}' method="post">
							{% csrf_token %}
							<input type="hidden" name="oid" value={{ order.oid }}>
							<input type="hidden" name="pid" value={{ item.pid }}>
						<td>
							<input type="number" name="price" min="0" step="0.01" value={{ item.oprice }}>
						</td>
						<td>
							<input type="number" name="quantity" min="1" value={{ item.oquantity }}>
						</td>
						<td>
							<center>
							<input class="btn btn-primary btn-sm" type="submit" value="&#9935">
							</center>
						</td>	
						</form>


						<td>
							<center>
							<form action='{% url 'backend:removefromcart' %}' method="post">
								{% csrf_token %}
								<input type="hidden" name="oid" value={{ order.oid }}>
								<input type="hidden" name="pid" value={{ item.pid }}>
								<input class="btn btn-primary btn-sm" type="submit" value="&#9876">
							</form>
							</center>
						</td>
					</tr>	
					{% endfor %}
				</table>

			</div>
		</div>
	{% else %}
	    <p>No items in the shopping cart.</p>
	{% endif %}

	<div class="container">
	
		<h5>Subtotal: {{ subtotal }}</h5>
		
		<br>
		<div class="row">
			<div class="col-1 mr-4">
		<form action='{% url 'backend:selectcustomer' %}' method="post">
			{% csrf_token %}
			<input type="hidden" name="oid" value={{ order.oid }} >
			<input type="submit" class="btn btn-warning" value="Checkout">
		</form>
			</div>

			<div class="col-1 ml-2">
				<a href='{% url 'backend:order_detail' order.oid %}' class="btn btn-info">Back To Order</a>
			</div>
		</div>
	</div>

		
	<hr>
	</div>

	<div class="container">

		<ul class="nav nav-tabs" id="myTab" role="tablist">
		  <li class="nav-item">
		    <a class="nav-link active" id="home-tab" data-toggle="tab" href="#food" role="tab" aria-controls="home" aria-selected="true">Food</a>
		  </li>
		  <li class="nav-item">
		    <a class="nav-link" id="profile-tab" data-toggle="tab" href="#health" role="tab" aria-controls="profile" aria-selected="false">Health</a>
		  </li>
		  <li class="nav-item">
		    <a class="nav-link" id="contact-tab" data-toggle="tab" href="#book" role="tab" aria-controls="contact" aria-selected="false">Book</a>
		  </li>
		</ul>
		<div class="tab-content" id="myTabContent">
		  <div class="tab-pane fade show active" id="food" role="tabpanel" aria-labelledby="home-tab">
			{% if foodproduct %}
				<div class="row">
					<div class="col">
						<table class="table table-striped table-hover">
							<thead class="thead-dark">
							<tr>
								<th style="width:30%;">Product</th>
								<th style="width:15%">Cost</th>
								<th style="width:15%;">Price</th>
								<th style="width:10%;">SOH</th>
								<th style="width:15%;">Actual Price</th>
								<th style="width:15%;">Quantity</th>

							</tr>
							</thead>
							{% for fp in foodproduct %}
							<tr>
								<td><a href='{% url 'backend:product_detail' fp.pid %}'> {{ fp.pname }} </a></td>
								<td> {{ fp.pcost }} </td>
								<td> {{ fp.pprice }} </td>
								<td> {{ fp.soh }} </td>
								
								<form action='{% url 'backend:addtocart' %}' method="post">
									{% csrf_token %}
									<input type="hidden" name="oid" value={{ order.oid }}>
									<input type="hidden" name="pid" value={{ fp.pid }}>
								<td>
									<input type="number" name="price" min="0" step="0.01" style="width:80px;" value={{ fp.pprice }}>
								</td>
								<td>
									<input type="number" name="quantity" min="1" value="1" style="width:80px;">
								
									<input class="btn btn-primary btn-sm" type="submit" value="+">
								</td>
								</form>
								</td>
							</tr>	
							{% endfor %}
						</table>
					</div>
				</div>
			{% else %}
			    <p>No products are available.</p>
			{% endif %}
		  </div>
		  <div class="tab-pane fade" id="health" role="tabpanel" aria-labelledby="profile-tab">
			{% if healthproduct %}
				<div class="row">
					<div class="col">
						<table class="table table-striped table-hover">
							<thead class="thead-dark">
							<tr>
								<th style="width:30%;">Product</th>
								<th style="width:15%">Cost</th>
								<th style="width:15%;">Price</th>
								<th style="width:10%;">SOH</th>
								<th style="width:15%;">Actual Price</th>
								<th style="width:15%;">Quantity</th>

							</tr>
							</thead>
							{% for hp in healthproduct %}
							<tr>
								<td><a href='{% url 'backend:product_detail' hp.pid %}'> {{ hp.pname }} </a></td>
								<td> {{ hp.pcost }} </td>
								<td> {{ hp.pprice }} </td>
								<td> {{ hp.soh }} </td>
								
								<form action='{% url 'backend:addtocart' %}' method="post">
									{% csrf_token %}
									<input type="hidden" name="oid" value={{ order.oid }}>
									<input type="hidden" name="pid" value={{ hp.pid }}>
								<td>
									<input type="number" name="price" min="0" step="0.01" style="width:80px;" value={{ hp.pprice }}>
								</td>
								<td>
									<input type="number" name="quantity" min="1" value="1" style="width:80px;">
								
									<input class="btn btn-primary btn-sm" type="submit" value="+">
								</td>
								</form>
								</td>
							</tr>	
							{% endfor %}
						</table>
					</div>
				</div>
			{% else %}
			    <p>No products are available.</p>
			{% endif %}
		  </div>
		  <div class="tab-pane fade" id="book" role="tabpanel" aria-labelledby="contact-tab">
			<p>No products are available.</p>
		  </div>

		</div>
	</div>



{% endblock %}